language: node_js
os: linux-ppc64le
dist: xenial
#sudo: false

node_js:
  - "node"
install:
  - npm i -g npm@5.8.0
  - npm ci
script:
  - npm run examples:lint
  - npm run examples:test
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
